test for libtool
git-svn-id: svn+ssh://cataclysm.cx/home/fce2/svn/repos/amber@4 ed6cb1fb-4f03-0410-806b-8831b9565825

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -10,5 +10,9 @@ if test -z "`automake --version 2>&1|head -n 1|egrep '1.[89]'`"; then
 	exit 1;
 fi
 
-# Fire up autotools
+if test -z "`libtool --version 2>&1|head -n 1|egrep '1.5'`"; then
+	echo "Libtool 1.5+ is required. Aborting build...";
+	exit 1;
+fi
+
 libtoolize --force --copy && aclocal && autoheader && automake --include-deps --add-missing --copy && autoconf 
